# Generated by Django 5.0.2 on 2024-03-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telscrapper', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('access_hash', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('group_id', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('was_online', models.DateTimeField(null=True)),
            ],
        ),
    ]
