# Generated by Django 5.0.4 on 2024-04-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('dripfeed', models.BooleanField()),
                ('refill', models.BooleanField()),
                ('cancel', models.BooleanField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
